const express = require('express')
const router = express.Router()
const authenticate  = require('../middleware/authenticate')
const controllers = require('../controllers/userController')
const upload =  require('../middleware/upload')
router.post('/register',upload.single('profilePic'),controllers.register)
router.post('/login',authenticate.authenticating,controllers.login)
router.post('/addMark',authenticate.authenticating,authenticate.admin,controllers.subject),
router.put('/updateMark',authenticate.authenticating,authenticate.admin,controllers.updateSubject)
router.delete('/deleteMark',authenticate.authenticating,authenticate.admin,controllers.deleteSubject)
router.get('/getMark1',authenticate.authenticating,authenticate.admin,controllers.singleUser)
router.get('/getMark',authenticate.authenticating,authenticate.admin,controllers.totalUser)
router.get('/getstudent',authenticate.authenticating,authenticate.admin,controllers.studentList)
router.get('/subjectwise',authenticate.authenticating,authenticate.admin,controllers.subjectwiseMark)
router.get('/total',authenticate.authenticating,authenticate.admin,controllers.totalSingleUser)
router.get('/rank',authenticate.authenticating,authenticate.admin,controllers.rank)
router.get('/studentId',authenticate.authenticating,authenticate.admin,controllers.studentId)
router.put('/upload',authenticate.authenticating,upload.single('profilePic'),controllers.uploadimage)
router.post('/execl',upload.single('Execl'),controllers.execl)
router.put('/execl1',authenticate.authenticating,upload.single('Execl'),controllers.execl1)
module.exports =router    