const express = require('express')
const router = express.Router()
const authenticate  = require('../middleware/authendicate')
const controllers = require('../controllers/userController')
const upload = require('../middleware/upload')
router.post('/register',controllers.register)
router.post('/login',controllers.login)
router.post('/stripePayment',authenticate.authenticating,controllers.stripePayment)
router.get('/listStripe',authenticate.authenticating,controllers.listStripe)
router.post('/chagre',authenticate.authenticating,controllers.chagre)
router.put('/updatecard',authenticate.authenticating,controllers.updateCard)
router.delete('/deleteCard',authenticate.authenticating,controllers.deleteCard)
router.post('/upload/product',authenticate.authenticating,upload.single('Execl'),controllers.uploadproduct)
router.post('/orderplace',authenticate.authenticating,controllers.orderplace)
router.post('/paymentMethod',authenticate.authenticating,controllers.paymentMethod)
router.post('/paymentMethod2',authenticate.authenticating,controllers.paymentMethod2)
module.exports =router  